Hw04 auth
Lorat1403/nodejs-hw-rest-api pull request #4
Opened 2022-12-26 08:40 UTC by Lorat1403

2022-12-26 20:06 UTC, BohdanGres requested changes

2022-12-26 20:06 UTC, BohdanGres commented on app.js
>  app.use("/api/contacts", contactsRouter);
можеш сюди мідлварку навісіти одразу, але перевір чи помилки правильно хендляться

2022-12-26 20:06 UTC, BohdanGres commented on middlewares/authenticate.js
> +    if (!user || !user.token) {
забула перевірити  user.token === token

2022-12-27 10:20 UTC, Lorat1403 commented on app.js
>  app.use("/api/contacts", contactsRouter);
в мене мідлварки у рутах, якось так вже звикла...

2022-12-27 10:20 UTC, Lorat1403 commented on middlewares/authenticate.js
> +    if (!user || !user.token) {
+

2022-12-27 10:22 UTC, Lorat1403 commented on middlewares/authenticate.js
> +    if (!user || !user.token) {
ок

2023-01-05 17:14 UTC, BohdanGres approved these changes

2023-01-05 17:36 UTC, merged