branch completed
Lorat1403/nodejs-hw-rest-api pull request #6
Opened 2023-01-16 15:55 UTC by Lorat1403

2023-01-16 19:22 UTC, BohdanGres requested changes
все доре трошки підчистити треба

2023-01-16 19:22 UTC, BohdanGres commented on controllers/auth/register.js
> +require("dotenv").config();
цю штуку треба викликати в файлу з якого все стартує і тільки 1 раз

2023-01-17 08:12 UTC, Lorat1403 commented on controllers/auth/register.js
> +require("dotenv").config();
зроблено)

2023-01-17 21:00 UTC, BohdanGres approved these changes

2023-01-18 17:08 UTC, merged